name: Build and Package Python Script

on:
  push:
    branches:
      - main  # or the branch you want to trigger the build on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build executable
      run: pyinstaller --onefile main.py

    - name: List dist directory
      run: ls -l dist

    - name: Generate version number
      id: version
      run: echo "::set-output name=version::$(date +'%Y.%m.%d')"

    - name: Rename executable with version
      run: mv dist/local-profile-manager dist/local-profile-manager_$(date +'%Y.%m.%d').exe

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: executable
        path: dist/local-profile-manager_$(date +'%Y.%m.%d').exe
