name: Build and Package Python Script
on:
  push:
    branches:
      - main
env:
  version: "${{ github.run_number }}"
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Print environment variables (debug)
      run: |
        echo "Version: ${{ env.version }}"
        echo "Python location: ${{ env.pythonLocation }}"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: Build executable
      run: pyinstaller --onefile --noupx --noconsole --add-data "config/config.json;config" main.py
    - name: Rename executable with version
      run: |
        echo "Renaming file with version: ${{ env.version }}"
        cd dist
        Rename-Item main.exe local-profile-manager_${{ env.version }}.exe
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: executable
        path: local-profile-manager_v${{ env.version }}.exe
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v${{ env.version }}"
        release_name: "Release v${{ env.version }}"
        draft: false
        prerelease: false
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: local-profile-manager_v${{ env.version }}.exe
        asset_name: local-profile-manager_v${{ env.version }}.exe
        asset_content_type: application/octet-stream